In [1]:
import pandas as pd

ic_df=pd.read_csv('insurance_claims.csv')

ic_df

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,48,521585,17-10-2014,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,42,342868,27-06-2006,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,29,687698,06-09-2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,41,227811,25-05-1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,44,367455,06-06-2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,38,941851,16-07-1991,OH,500/1000,1000,1310.80,0,431289,...,1,?,87200,17440,8720,61040,Honda,Accord,2006,N
996,285,41,186934,05-01-2014,IL,100/300,1000,1436.79,0,608177,...,3,?,108480,18080,18080,72320,Volkswagen,Passat,2015,N
997,130,34,918516,17-02-2003,OH,250/500,500,1383.49,3000000,442797,...,3,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N
998,458,62,533940,18-11-2011,IL,500/1000,2000,1356.92,5000000,441714,...,1,YES,46980,5220,5220,36540,Audi,A5,1998,N
999,456,60,556080,11-11-1996,OH,250/500,1000,766.19,0,612260,...,3,?,5060,460,920,3680,Mercedes,E400,2007,N

In [2]:
ic_df.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported'],
      dtype='object')

In [3]:
ic_df.shape

(1000, 39)

In [4]:
ic_df.isnull().sum()

months_as_customer             0
age                            0
policy_number                  0
policy_bind_date               0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
insured_zip                    0
insured_sex                    0
insured_education_level        0
insured_occupation             0
insured_hobbies                0
insured_relationship           0
capital-gains                  0
capital-loss                   0
incident_date                  0
incident_type                  0
collision_type                 0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
incident_location              0
incident_hour_of_the_day       0
number_of_vehicles_involved    0
property_damage                0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
fraud_reported                 0
dtype: int64

In [5]:
ic_df['fraud_reported']

0      Y
1      Y
2      N
3      Y
4      N
      ..
995    N
996    N
997    N
998    N
999    N
Name: fraud_reported, Length: 1000, dtype: object

In [6]:
ic_df['fraud_reported'].replace({'Y':1,'N':0},inplace=True)

ic_df['fraud_reported']

0      1
1      1
2      0
3      1
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: fraud_reported, Length: 1000, dtype: int64

# Chi-Square

In [7]:
from scipy.stats import chi2_contingency as chi
chi_corr_cat_cols=[]
chi_non_corr_cols=[]
def chi_square(df,out_column):
    cat_cols=[col for col in df.columns if df[col].dtype=='object']
    for col in cat_cols:
        contingency_table=pd.crosstab(df[col],df[out_column])
        p_value=chi(contingency_table)[1]
        if p_value<0.05:
            chi_corr_cat_cols.append(col)
        else:
            chi_non_corr_cols.append(col)
            
    
chi_square(ic_df,'fraud_reported')

print(chi_corr_cat_cols)

['insured_hobbies', 'incident_type', 'collision_type', 'incident_severity', 'authorities_contacted', 'incident_state', 'property_damage']

In [8]:
print(chi_non_corr_cols)

['policy_bind_date', 'policy_state', 'policy_csl', 'insured_sex', 'insured_education_level', 'insured_occupation', 'insured_relationship', 'incident_date', 'incident_city', 'incident_location', 'police_report_available', 'auto_make', 'auto_model']

# Anova

In [9]:
cont_cols=[col for col in ic_df.columns if ic_df[col].dtype=='int64' or ic_df[col].dtype=='float64']
from scipy.stats import f_oneway
anova_corr_cols=[]
anova_non_corr_cols=[]
for col in cont_cols:
    
    y_list=list(ic_df[ic_df['fraud_reported']=='Y'][col])
    n_list=list(ic_df[ic_df['fraud_reported']=='N'][col])
    p_value=f_oneway(y_list,n_list)[1]
    if p_value<0.05:
        anova_corr_cols.append(col)
    else:
        anova_non_corr_cols.append(col)
print(anova_corr_cols)
print(anova_non_corr_cols)

C:\Users\User\anaconda3\lib\site-packages\scipy\stats\stats.py:3680: F_onewayBadInputSizesWarning: at least one input has length 0
  warnings.warn(F_onewayBadInputSizesWarning('at least one input '

[]
['months_as_customer', 'age', 'policy_number', 'policy_deductable', 'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'capital-gains', 'capital-loss', 'incident_hour_of_the_day', 'number_of_vehicles_involved', 'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim', 'property_claim', 'vehicle_claim', 'auto_year', 'fraud_reported']

In [10]:
Total_non_corr=chi_non_corr_cols+anova_non_corr_cols

In [11]:
#identifying the columns tp drop
cols_to_drop=[]
for col in ic_df.columns:
    if ic_df[col].nunique()==1 or ic_df[col].nunique()==ic_df.shape[0]:
        cols_to_drop.append(col)
        
cols_to_drop+=Total_non_corr
cols_to_drop.append('fraud_reported')
cols_to_drop

['policy_number',
 'incident_location',
 'policy_bind_date',
 'policy_state',
 'policy_csl',
 'insured_sex',
 'insured_education_level',
 'insured_occupation',
 'insured_relationship',
 'incident_date',
 'incident_city',
 'incident_location',
 'police_report_available',
 'auto_make',
 'auto_model',
 'months_as_customer',
 'age',
 'policy_number',
 'policy_deductable',
 'policy_annual_premium',
 'umbrella_limit',
 'insured_zip',
 'capital-gains',
 'capital-loss',
 'incident_hour_of_the_day',
 'number_of_vehicles_involved',
 'bodily_injuries',
 'witnesses',
 'total_claim_amount',
 'injury_claim',
 'property_claim',
 'vehicle_claim',
 'auto_year',
 'fraud_reported',
 'fraud_reported']

In [12]:
ic_df.drop(columns=cols_to_drop,inplace=True)# dropping all the identified columns(from the above steps

In [13]:
cat_cols=[col for col in ic_df.columns if ic_df[col].dtype=='object']
con_cols=[col for col in ic_df.columns if ic_df[col].dtype=='int64' or ic_df[col].dtype=='float64']

print("categorical cols:",cat_cols)
print("continuous cols:",con_cols)

categorical cols: ['insured_hobbies', 'incident_type', 'collision_type', 'incident_severity', 'authorities_contacted', 'incident_state', 'property_damage']
continuous cols: []